/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'RunCode': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ConfigurePtrJob': EventHandler<never, never>
    'ConfigureDMARCJob': EventHandler<never, never>
    'ConfigureDKIMJob': EventHandler<never, never>
    'CreateServerJob': EventHandler<never, never>
    'BasicDnsCreateJob': EventHandler<never, never>
    'ConfigurePRT': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'configure.ptr'; data: never }>
    'ConfigureDMARC': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'configure.dmarc'; data: never }>
    'ConfigureDKIM': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'configure.dkim'; data: never }>
    'GetSSHKeys': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetServers': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetServerStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateServer': ApiRouteHandler<{ plan: 'plan1' | 'plan2'; username: string; domain: string }, unknown, { topic: 'server.create'; data: never }>
    'SetupDNS': ApiRouteHandler<{ domain: string; ipaddress: string }, unknown, { topic: 'dns.basic.create'; data: never }>
    'checkStatus': CronHandler<never>
    'checkDomainDns': CronHandler<never>
    'checkDmarcStatus': CronHandler<{ topic: 'configure.dmarc'; data: never }>
    'FetchMailcowTokenJob': EventHandler<never, never>
    'CreateMailcowDomainJob': EventHandler<never, never>
    'CreateMailboxesJob': EventHandler<never, never>
    'GetMailboxes': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDomains': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDomainDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FetchMailcowToken': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'fetch.mailcow.apitoken'; data: never }>
    'GetMailcowDKIMJob': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateMailcowDomain': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'create.mailcow.domain'; data: never }>
    'CreateMailboxes': ApiRouteHandler<{ domain: string; count: number }, unknown, { topic: 'create.mailboxes'; data: never }>
    'QueryDomain': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'QueryDomainStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'NamecheapCreateDomain': ApiRouteHandler<{ domainName: string; years: unknown; registrant: { firstName: string; lastName: string; address1: string; city: string; stateProvince: string; postalCode: string; country: string; phone: string; emailAddress: string; organizationName?: string }; admin: { firstName: string; lastName: string; address1: string; city: string; stateProvince: string; postalCode: string; country: string; phone: string; emailAddress: string; organizationName?: string }; tech: { firstName: string; lastName: string; address1: string; city: string; stateProvince: string; postalCode: string; country: string; phone: string; emailAddress: string; organizationName?: string }; auxBilling: { firstName: string; lastName: string; address1: string; city: string; stateProvince: string; postalCode: string; country: string; phone: string; emailAddress: string; organizationName?: string }; addFreeWhoisguard?: boolean; wgEnabled?: boolean; isPremiumDomain?: boolean; premiumPrice?: number; eapFee?: number }, unknown, never>
    'Tester': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Signup': ApiRouteHandler<{ firstname: string; lastname: string; email: string; password: string }, unknown, never>
    'Login': ApiRouteHandler<{ email: string; password: string }, unknown, never>
  }
    
}